self.addEventListener('install',(event)=>{
     event.waitUntil(
   caches.open('lala').then(Cache=>{
        Cache.addAll(
             [
                  "/",
                  "index.html"
                  ]
             )
   })       
         )
})